spring :
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:STUDY_CAFE_APPLICATION
    username: sa
    password:
